CC = gcc
AR = ar rs
CFLAGS = -g -W -Wall -Werror -I../include -MMD -fprofile-arcs -ftest-coverage
LDFLAGS = -g -fprofile-arcs -ftest-coverage

default: all

.PHONY: clean
clean: clean_impl
	@rm -f $(OBJS:%.o=%.c.gcov) $(OBJS:%.o=%.gcda) $(OBJS:%.o=%.gcno)
